### PR TITLE
`@DeprecationSummary` not having effect for some symbols

### LINKED ISSUE #932: `@DeprecationSummary` directive doesn't always have an effect
### Description

When specifying the `@DeprecationSummary` directive in a symbol extension markdown file, the directive doesn't take effect if the symbol has documentation.

If you define a symbol with multiple lines of source code documentation, and then attempt to deprecate the symbol from a symbol extension markdown file, the result is that the symbol is not deprecated as expected.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I expected the symbol `ExampleDeprecated` to be marked as deprecated in my documentation, like this:
Screenshot 2024-05-29 at 16 14 45

### Actual behavior

But in actuality, the `@DeprecationSummary` directive has no effect when using the default merge behaviour (`append`), and the result is the following:
Screenshot 2024-05-29 at 16 12 33

I can only get the `@DeprecationSummary` directive to have an effect when setting the merge behaviour to be `override`:
```md
@Metadata {
    @DocumentationExtension(mergeBehavior: override)
}
```

### Steps To Reproduce

1. Define a symbol and add multiple lines of documentation in the source code, like so:
```swift
/// I am adding some amazing documentation for my new struct.
///
/// ## Overview
///
/// In fact it's so cool, that it even needs some markdown.
public struct ExampleDeprecated {}
```
2. Deprecate the symbol from a symbol extension markdown file:
```md
# ``ExampleDeprecated``

@DeprecationSummary {
 This is my deprecation text.
}

This struct is deprecated because I needed an example.
```

### Swift-DocC Version Information

037f0bcca7b1aa75551bd9b46825287c159a86b5

### Swift Compiler Version Information

```shell
❯ swiftc --version
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx15.0
```

### PR DESCRIPTION
**Pull request by anferbui**
Bug/issue #, if applicable: Closes #932, rdar://70056350.

## Summary

Fixes a bug where the `@DeprecationSummary` directive would have no effect if a symbol had multiple lines of documentation comments in its source, like so:
```swift
/// I am adding some amazing documentation for my new struct.
///
/// ## Overview
///
/// In fact it's so cool, that it even needs some markdown.
public struct ExampleDeprecated {}
```

The root cause of the issue was that the `@DeprecatedSummary` directive would only take effect when used in the "Abstract" section of the markup.

When using the default merging strategy for documentation extension files (`append`), documentation extension content is added after all the existing documentation comments, resulting in something like:
```md
I am adding some amazing documentation for my new struct.

## Overview

In fact it's so cool, that it even needs some markdown.

@DeprecationSummary {
    This symbol is deprecated.
}
```

This would make the `@DeprecationSummary` directive be in the Discussion section, not the Abstract, so it would be ignored. This made it impossible to override the deprecation summary from the documentation extension file for any symbols which had multiple lines of documentation comments. (It worked fine if the symbol has no source documentation or only one line of source documentation).

This PR makes it so that the `@DeprecationSummary` can be parsed in both the Abstract and Discussion sections.

## Dependencies

N/A.

## Testing

You need the following setup:
- A symbol with multiple lines of documentation in the source code
- A documentation extension file which uses the `@DeprecationSummary` directive, for example.

Example DocC bundle:
[TestPackage.docc.zip](https://github.com/user-attachments/files/16177976/TestPackage.docc.zip)

Steps:
1. Download example bundle
2. Run `docc preview TestPackage.docc`
3. Go to http://localhost:8080/documentation/testpackage/exampledeprecated and verify that the symbol is marked as deprecated.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- ~~[ ] Updated documentation if necessary~~ **Not necessary**

### Verification

**Unit testing**
Added unit tests to `DocumentationMarkupTests` and `DeprecationSummaryTests `.

```
[1703/1703] Testing SwiftDocCTests.SynchronizationTests/testBlockingWithLock
=> Checking for unacceptable language… okay.
=> Checking license headers… okay.
=> Validating scripts in bin subdirectory… okay
```

**Site rendering**

Before                                  |  After
:-------------------------:|:-------------------------:
Screenshot 2024-07-11 at 2 50 47 PM | Screenshot 2024-07-11 at 2 51 23 PM

### CODE REVIEW

**Comment by anferbui** [comment]
@swift-ci please test

File: Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift [hunk 1]
```diff
@@ -181,4 +181,66 @@ class DeprecationSummaryTests: XCTestCase {
...
+        )
+        
+        // Compile docs and verify contents
+        let symbol = node.semantic as! Symbol
+        var translator = RenderNodeTranslator(context: context, bundle: bundle, identifier: node.reference)
+        
+        guard let renderNode = translator.visit(symbol) as? RenderNode else {
+            XCTFail("Could not compile the node")
+            return
+        }
```
Comment (d-ronnqvist) [inline Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift:237]: nit: using `XCTUnwrap` is a more succinct way to assert that a value is non-`nil`
```suggestion
        let renderNode = try XCTUnwrap(translator.visit(symbol) as? RenderNode)
```

File: Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift [hunk 2]
```diff
@@ -181,4 +181,66 @@ class DeprecationSummaryTests: XCTestCase {
...
+        
+        // `init(config:cache:)` has deprecation information in both the symbol graph and the documentation extension; the symbol graph has multiple lines of documentation comments for the function, but adding deprecation information in the documentation extension should still work.
+        let expected: [RenderInlineContent] = [
+            .text("This initializer is deprecated as of version 1.0.0."),
+        ]
+        
+        XCTAssertEqual(renderNode.deprecationSummary?.firstParagraph, expected)
```
Comment (d-ronnqvist) [inline Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift:244]: nit: it's not necessary to define the `expected` variable if it's only used once in a test assertion (which should be able to infer its type)
```suggestion
        XCTAssertEqual(renderNode.deprecationSummary?.firstParagraph, [
            .text("This initializer is deprecated as of version 1.0.0."),
        ])
```

File: Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift [hunk 3]
```diff
@@ -181,4 +181,66 @@ class DeprecationSummaryTests: XCTestCase {
...
+        )
+        
+        // Compile docs and verify contents
+        let symbol = node.semantic as! Symbol
+        var translator = RenderNodeTranslator(context: context, bundle: bundle, identifier: node.reference)
+        
+        guard let renderNode = translator.visit(symbol) as? RenderNode else {
+            XCTFail("Could not compile the node")
+            return
+        }
```
Comment (d-ronnqvist) [inline Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift:202]: nit: using XCTUnwrap is a more succinct way to assert that a value is non-nil
```suggestion
        let renderNode = try XCTUnwrap(translator.visit(symbol) as? RenderNode)
```

File: Sources/SwiftDocC/Model/DocumentationMarkup.swift [hunk 4]
```diff
@@ -74,12 +74,17 @@ struct DocumentationMarkup {
     }
     
     /// Directives which are removed from the markdown content after being parsed.
-    private static let directivesRemovedFromContent = [
+    internal static let directivesRemovedFromContent = [
```
Comment (d-ronnqvist) [inline Sources/SwiftDocC/Model/DocumentationMarkup.swift:77]: nit: `internal` is the default access level
```suggestion
    static let directivesRemovedFromContent = [
```

**Review by d-ronnqvist — APPROVED** [review]
LGTM

File: Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift (hunk 1 above)
Comment (anferbui) [reply Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift]: Thank you, I copy&pasted previous tests and failed to notice this. Reworked the whole file to use `XCTUnwrap` where appropriate!

**Comment by anferbui** [comment]
@swift-ci please test
